### ISSUE TITLE
Not an issue, but feedback and a question

### ISSUE THREAD

**Issue by shavitush** [TotallyMehis/StandUp#3]
Hey, been using the plugin for my CS:S KZ/scroll-bhop and it works just fine with [my bhop timer](https://github.com/shavitush/bhoptimer).

I use the modules:
- standup_chatrecords
- standup_core
- standup_core_ljmode (edited so only 100 airaccelerate, non-easy and scroll styles can use it)
- standup_help
- standup_hud
- standup_hud_blocks
- standup_hud_chatrecords
- standup_restartmap

(That's my feedback so far - no issues at all with my timer using [this ljmode source](https://gist.github.com/shavitush/3ad894d899b44287a99372baed6642b0))

And I have a question: sometimes I get '(true: xxx.xxx)' and I have no idea what it means. Tried going through the source to understand and it really confused me :o

**Comment by TotallyMehis** [comment]
Sorry for taking so long to answer, I had my watch notifications off for some reason.

True distance is the actual distance the player has jumped. Eg. jumping diagonally makes your distance actually higher because player hulls are a box (-16,-16) to (16,16) meaning you get an extra 12~ units (sqrt(16^2 + 16^2) for jump and landing).

The normal distance takes into account this anomaly (instead of using hulls, it uses a circle) because then players could cheat, getting higher distances by jumping diagonally.

**Comment by shavitush** [comment]
I see, thanks!
